/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YkHkQC8mTx5
 */
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { CardTitle, CardDescription, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { DialogTrigger, DialogTitle, DialogHeader, DialogContent, DialogFooter, Dialog } from "@/components/ui/dialog"

export function Homepage() {
  return (
    <main className="flex flex-col lg:flex-row gap-6 lg:gap-10 p-4 md:p-6">
      <aside className="flex flex-col gap-6 lg:w-64">
        <div className="flex items-center gap-4">
          <FilmIcon className="w-8 h-8" />
          <h1 className="text-2xl font-bold">MovieMate</h1>
        </div>
        <form className="flex items-center gap-4">
          <SearchIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
          <Input className="flex-1" placeholder="Search movies..." type="search" />
        </form>
        <div className="space-y-6">
          <fieldset>
            <legend className="font-semibold mb-4 text-sm">Genre</legend>
            <div className="grid gap-2">
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="genre-action" />
                Action{"\n"}
              </Label>
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="genre-comedy" />
                Comedy{"\n"}
              </Label>
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="genre-drama" />
                Drama{"\n"}
              </Label>
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="genre-horror" />
                Horror{"\n"}
              </Label>
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="genre-romance" />
                Romance{"\n"}
              </Label>
            </div>
          </fieldset>
          <fieldset>
            <legend className="font-semibold mb-4 text-sm">Rating</legend>
            <div className="grid gap-2">
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="rating-g" />
                G{"\n"}
              </Label>
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="rating-pg" />
                PG{"\n"}
              </Label>
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="rating-pg13" />
                PG-13{"\n"}
              </Label>
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="rating-r" />
                R{"\n"}
              </Label>
            </div>
          </fieldset>
          <fieldset>
            <legend className="font-semibold mb-4 text-sm">Release Year</legend>
            <div className="grid gap-2">
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="year-2020" />
                2020{"\n"}
              </Label>
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="year-2019" />
                2019{"\n"}
              </Label>
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="year-2018" />
                2018{"\n"}
              </Label>
              <Label className="flex items-center gap-2 font-normal">
                <Checkbox id="year-2017" />
                2017{"\n"}
              </Label>
            </div>
          </fieldset>
        </div>
      </aside>
      <section className="flex-1 space-y-6">
        <h2 className="text-2xl font-bold mb-4">Netflix</h2>
        <div className="flex space-x-8 overflow-x-scroll">
          <Card className="w-full">
            <div />
            <CardContent>
              <CardTitle className="text-lg font-semibold">Netflix Movie 1</CardTitle>
              <CardDescription className="text-sm text-gray-500 dark:text-gray-400">Rating: 4.5</CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <div />
            <CardContent>
              <CardTitle className="text-lg font-semibold">Netflix Movie 2</CardTitle>
              <CardDescription className="text-sm text-gray-500 dark:text-gray-400">Rating: 4.2</CardDescription>
            </CardContent>
          </Card>
        </div>
        <h2 className="text-2xl font-bold mb-4">Amazon Prime</h2>
        <div className="flex space-x-8 overflow-x-scroll">
          <Card className="w-full">
            <div />
            <CardContent>
              <CardTitle className="text-lg font-semibold">Amazon Prime Movie 1</CardTitle>
              <CardDescription className="text-sm text-gray-500 dark:text-gray-400">Rating: 4.8</CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <div />
            <CardContent>
              <CardTitle className="text-lg font-semibold">Amazon Prime Movie 2</CardTitle>
              <CardDescription className="text-sm text-gray-500 dark:text-gray-400">Rating: 4.1</CardDescription>
            </CardContent>
          </Card>
        </div>
        <h2 className="text-2xl font-bold mb-4">Hotstar</h2>
        <div className="flex space-x-8 overflow-x-scroll">
          <Card className="w-full">
            <div />
            <CardContent>
              <CardTitle className="text-lg font-semibold">Hotstar Movie 1</CardTitle>
              <CardDescription className="text-sm text-gray-500 dark:text-gray-400">Rating: 4.3</CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <div />
            <CardContent>
              <CardTitle className="text-lg font-semibold">Hotstar Movie 2</CardTitle>
              <CardDescription className="text-sm text-gray-500 dark:text-gray-400">Rating: 4.7</CardDescription>
            </CardContent>
          </Card>
        </div>
      </section>
      <Dialog>
        <DialogTrigger asChild>
          <Button variant="link">Movie Details</Button>
        </DialogTrigger>
        <DialogContent className="w-96">
          <DialogHeader>
            <DialogTitle>Movie Title</DialogTitle>
          </DialogHeader>
          <DialogContent>
            <div className="grid gap-4">
              <div className="grid gap-2">
                <h4 className="font-semibold">Synopsis</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">This is a brief summary of the movie.</p>
              </div>
              <div className="grid gap-2">
                <h4 className="font-semibold">Cast</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">Actor 1, Actor 2, Actor 3</p>
              </div>
              <div className="grid gap-2">
                <h4 className="font-semibold">Director</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">Director Name</p>
              </div>
            </div>
          </DialogContent>
          <DialogFooter>
            <Button>Watch Trailer</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </main>
  )
}


function FilmIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M7 3v18" />
      <path d="M3 7.5h4" />
      <path d="M3 12h18" />
      <path d="M3 16.5h4" />
      <path d="M17 3v18" />
      <path d="M17 7.5h4" />
      <path d="M17 16.5h4" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
